#!/bin/sh

TOP_DIR="$(dirname "$(realpath "$0")")"

set_guix_env () {
    channel_path="$TOP_DIR/$1"
    export GUILE_LOAD_COMPILED_PATH="${channel_path}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
    export GUILE_LOAD_PATH="${channel_path}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
    export PATH="${channel_path}/scripts:$PATH"
    export GUIX="${channel_path}/scripts/guix"
    export GUIX_UNINSTALLED=1
}

set_channel_env () {
    channel_path="$TOP_DIR/$1"
    export GUILE_LOAD_PATH="${channel_path}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
    export GUIX_PACKAGE_PATH="${channel_path}${GUIX_PACKAGE_PATH:+:}${GUIX_PACKAGE_PATH}"
}

set_guix_env    channels/guix
set_channel_env channels/nonguix
set_channel_env channels/rosenthal/modules
set_channel_env channels/sops-guix/modules

exec "$@"
