version = 1

[[annotations]]
path = [
        ".envrc",
        ".gitignore",
        ".guix-authorizations",
        "channels.lock",
        "channels.scm",
        "config/live/**",
        "dist/**",
        "files/**",
        "manifest.scm",
        "pre-inst-env",
       ]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["modules/installer/**"]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "GPL-3.0-or-later"
