version = 1

[[annotations]]
path = [
        "*.patch",
        "*.tmp",
        ".dir-locals.el",
        ".envrc",
        ".gitignore",
        ".gitmodules",
        ".guix-authorizations",
        ".sops.yaml",
        "channels-fork.lock",
        "channels.lock",
        "channels.scm",
        "deploy/*",
        "dist/**",
        "manifest.scm",
        "pre-inst-env",
        "scripts/**",
        "secrets/*",
       ]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
        "config/live/**",
        "modules/installer/**",
       ]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "GPL-3.0-or-later"
