# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

background-color=#E8E3E9E0
border-color=#E8E3E9
text-color=#2E3044
border-radius=5
font=monospace 11
