# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

font=monospace 11
text-color=#2E3044
background-color=#E8E3E9E0
border-size=1
border-color=#D0CAD9
border-radius=5
