# https://vcb-s.com/archives/7594
profile=high-quality
cscale=catmull_rom
deband=yes
blend-subtitles=video
video-sync=display-resample
interpolation=yes
tscale=oversample
sub-auto=fuzzy
hwdec=auto-safe

# uosc
osd-bar=no
border=no

fullscreen=yes
force-window=yes
idle=yes
screenshot-directory=/home/hako/Pictures/MPV/
screenshot-template="%F %P"
