# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

blend-subtitles=video
deband=yes
fullscreen=yes
gpu-api=vulkan
hwdec=auto
interpolation=yes
profile=high-quality
scale=ewa_lanczossharp
screenshot-directory=~/Library/Pictures/MPV/
screenshot-template="%F %P"
sub-auto=fuzzy
tscale=oversample
video-sync=display-resample
vo=gpu-next
