# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

transaction_log            /var/log/btrbk.log
lockfile                   /var/lock/btrbk.lock

snapshot_dir               @Snapshot
snapshot_create            onchange

snapshot_preserve          30d
snapshot_preserve_min      3d

volume /mnt/Mentha
subvolume @Data
subvolume @Home
