# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

[server]
bind = "127.0.0.1:54504"

[sources]
markov = [
    "$$iocaine/1984.txt$$",
    "$$iocaine/brave-new-world.txt$$"
]
words = "$$iocaine/words.txt$$"
