Create Both
Expunge Both
CopyArrivalDate yes

MaildirStore local
Path ~/.local/share/mail/imap/
Inbox ~/.local/share/mail/imap/INBOX
Subfolders Verbatim

IMAPAccount hako
Host mail.boiledscript.com
User "hako@ultrarare.space"
PassCmd "cat $XDG_RUNTIME_DIR/secrets/mail"
TLSType IMAPS

IMAPStore remote
Account hako

Channel hako
Far :remote:
Near :local:
Pattern *
SyncState *
