# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

Create Both
Expunge Both
CopyArrivalDate yes

MaildirStore local
Path ~/.local/share/mail/
Inbox ~/.local/share/mail/INBOX
Subfolders Verbatim

IMAPAccount hako
Host mail.boiledscript.com
User "hako@ultrarare.space"
PassCmd "cat $XDG_RUNTIME_DIR/secrets/mail"
TLSType IMAPS

IMAPStore remote
Account hako

Channel hako
Far :remote:
Near :local:
Pattern *
SyncState *
