# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

enabled = true;
sign_authenticated = true;
sign_local = true;

use_domain = "header";
use_redis = false;
use_esld = true;
check_pubkey = true;

domain {
    boiledscript.com {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-boiledscript.com.private.txt";
        selector = "mail";
    }
    ultrarare.space {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-ultrarare.space.private.txt";
        selector = "mail";
    }
    urspace.moe {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-urspace.moe.private.txt";
        selector = "mail";
    }
}
