# -*- mode: conf-space -*-
# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

bind 127.0.0.1:53
log-level notice
speed-check-mode tcp:80
response-mode fastest-ip


# Default Group
# Cloudflare
server-https 1.1.1.1/dns-query
server-https 1.0.0.1/dns-query
server-tls 1.1.1.1
server-tls 1.0.0.1

# Google
server-https 8.8.8.8/dns-query
server-https 8.8.4.4/dns-query
server-tls dns.google

# OpenDNS
server-https 146.112.41.2/dns-query

# Quad9
server-https dns.quad9.net/dns-query
server-tls dns.quad9.net


# Domestic Group
# DNSPod
server-https 1.12.12.12/dns-query -group domestic -exclude-default-group
server-https 120.53.53.53/dns-query -group domestic -exclude-default-group
server-tls 1.12.12.12 -group domestic -exclude-default-group
server-tls 120.53.53.53 -group domestic -exclude-default-group

# AliDNS
server-https dns.alidns.com/dns-query -group domestic -exclude-default-group
server-tls 223.5.5.5 -group domestic -exclude-default-group
server-tls 223.6.6.6 -group domestic -exclude-default-group

# 114 DNS
server-tcp 114.114.114.114 -group domestic -exclude-default-group
server-tcp 114.114.115.115 -group domestic -exclude-default-group

# CNNIC
server 1.2.4.8 -group domestic -exclude-default-group
server 210.2.4.8 -group domestic -exclude-default-group

conf-file $$share/dnsmasq-china-list/accelerated-domains.china.smartdns.conf$$
conf-file $$share/dnsmasq-china-list/apple.china.smartdns.conf$$
conf-file $$share/dnsmasq-china-list/bogus-nxdomain.china.smartdns.conf$$
