# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

[global]
address = ["127.0.0.1", "::1"]
port = 26372
server_name = "guix.moe"
database_path = "/var/lib/tuwunel"
new_user_displayname_suffix = ""
require_auth_for_profile_requests = true
allow_public_room_directory_over_federation = true
trusted_servers = ["matrix.org"]

[global.well_known]
client = "https://matrix.guix.moe"
server = "matrix.guix.moe:443"
